#!/bin/sh
if [ $# -eq 1 ]; then
	if ! [ -e "$1" ]; then	
		# 
		# Make the file ascii
		#
		touch "$1"
		chtag -tcISO8859-1 "$1"
	fi
fi
/bin/vi $*
rc=$?

if [ $# -eq 1 ]; then
	size=$(ls -s1 "$1" | awk '{print $1}')
	if [ $size -eq 0 ]; then
		rm "$1"
	fi
fi
	
	
